### ISSUE TITLE
cp4ba operators are in pending state 

### ISSUE THREAD

**Issue by prageetika** [apollo-business-automation/ibm-cp4ba-enterprise-deployment#26] opened 2023-01-06 14:27 UTC
**Describe the bug**
cp4ba operators are stuck in pending state 

![image](https://user-images.githubusercontent.com/24539315/211031187-1c1882b7-8ada-43d1-904b-fe27276d7efa.png)

**Comment by jandusek4** [comment] 2023-01-26 11:27
I believe this is caused by the OLM issue with async subscriptions which should be resolved in OCP 4.10.46+ and OCP 4.11.

**Closed as completed** 2023-01-26 11:41 UTC
Labels: bug
